temp - convert to RGB for compatibility
P - mode throws error: ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[18], line 1
----> 1 result = run('whole', 0.5, 'png', img_bytes, None)
      2 print(result['msg'])
      3 print(f"Output size: {len(result['output'])} bytes")

File ~/Documents/qbraid-test/platform-sandbox/QuantumBlur/quantumblur/basic.py:33, in run(blurStyle, blurStrength, imgForm, imgData, imgCoor)
     30 # *** SIMPLEST OPERATION for test ***
     31 if (style == 'whole'):
     32     # Process the image
---> 33     blur_circuits = blur_image(prevImg, blurStrength)
     34 elif (style == 'partial'): # c.f. Dealing with the selected region.
     35     # *** Dummy file ***
     36     region = imgCoor

File ~/Documents/qbraid-test/platform-sandbox/QuantumBlur/quantumblur/quantumblur.py:850, in blur_image(image, xi, circuits, axis, log)
    832 def blur_image(image, xi, circuits=None, axis='x',log=False):
    833     """
    834     Applies a predetermined blur effect designed for a smooth blur.
    835
   (...)    847         circuits (list): Circuits on which the blur effect has been
    848     """
--> 850     heights = _image2heights(image)
    852     if circuits==None:
    853         circuits=[None,None,None]

File ~/Documents/qbraid-test/platform-sandbox/QuantumBlur/quantumblur/quantumblur.py:183, in _image2heights(image)
    181         rgb = image.getpixel((x,y))
    182         for j in range(3):
--> 183             heights[j][x,y] = rgb[j]
    185 return heights

TypeError: 'int' object is not subscriptable